package com.company.Common.Display;

import java.util.List;

public class DisplayArrayCompByDB {
    public void display(List<int[]>hiberateResult, List<int[]>myBatisResult){
        System.out.println("");
        System.out.println("\t|===================+================================++===================+=================+");
        System.out.println("\t|     Catégorie     |            Functions           ||     Hibernate    |      MyBatis     |");
        System.out.println("\t|===================+================================++===================+=================+");
          System.out.print("\t|                   |  Select By ID                  ||" );
        System.out.printf("%11d",hiberateResult.get(0)[0]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(0)[0]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Select All                    ||" );
        System.out.printf("%11d",hiberateResult.get(0)[1]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(0)[1]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|    Fetch Test     +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Select With Constraints       ||" );
        System.out.printf("%11d",hiberateResult.get(0)[2]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(0)[2]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Select With Joins             ||" );
        System.out.printf("%11d",hiberateResult.get(0)[3]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(0)[3]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Select With Joins & Group BY  ||" );
        System.out.printf("%11d",hiberateResult.get(0)[4]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",hiberateResult.get(0)[4]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|===================+================================++===================+=================+");


          System.out.print("\t|                   |  Insert Single                 ||" );
        System.out.printf("%11d",hiberateResult.get(1)[0]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(1)[0]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Insert Bulk                   ||" );
        System.out.printf("%11d",hiberateResult.get(1)[1]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(1)[1]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Update Single                 ||" );
        System.out.printf("%11d",hiberateResult.get(1)[2]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(1)[2]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|     CUD Test      +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Update Bulk                   ||" );
        System.out.printf("%11d",hiberateResult.get(1)[3]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(1)[3]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Delete Single                 ||" );
        System.out.printf("%11d",hiberateResult.get(1)[4]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(1)[4]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Delete Bulk                   ||" );
        System.out.printf("%11d",hiberateResult.get(1)[5]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(1)[5]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|===================+================================++===================+=================+");


          System.out.print("\t|                   |  Select By ID                  ||" );
        System.out.printf("%11d",hiberateResult.get(2)[0]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(2)[0]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Select All                    ||" );
        System.out.printf("%11d",hiberateResult.get(2)[1]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(2)[1]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|    Stream Test    +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Select With Constraints       ||" );
        System.out.printf("%11d",hiberateResult.get(2)[2]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(2)[2]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Select With Joins             ||" );
        System.out.printf("%11d",hiberateResult.get(2)[3]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(2)[3]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   |  Select With Joins & Group BY  ||" );
        System.out.printf("%11d",hiberateResult.get(2)[4]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",myBatisResult.get(2)[4]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|===================+================================++===================+=================+");


          System.out.print("\t|                   |  Stored Procedure              ||" );
        System.out.printf("%11d",hiberateResult.get(3)[0]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",hiberateResult.get(3)[0]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|   Function Test   |  Inheritence                   ||" );
        System.out.printf("%11d",hiberateResult.get(3)[1]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",hiberateResult.get(3)[1]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|                   +--------------------------------++------------------+------------------+");
          System.out.print("\t|                   | Association                    ||" );
        System.out.printf("%11d",hiberateResult.get(3)[2]);
        System.out.printf("%8s","|");
        System.out.printf("%11d",hiberateResult.get(3)[2]);
        System.out.printf("%8s","|");
        System.out.println("");
        System.out.println("\t|===================+================================++===================+=================+");
    }
}
